"""Create Table Aluno

Revision ID: 33941231d0d0
Revises: 
Create Date: 2024-11-18 12:54:48.948979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33941231d0d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aluno',
    sa.Column('id_aluno', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_aluno')
    )
    op.create_table('Curso',
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('duracao', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['aluno.id_aluno'], ),
    sa.PrimaryKeyConstraint('id_curso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Curso')
    op.drop_table('aluno')
    # ### end Alembic commands ###
